languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "MeatyBytes"
logo = "img/MR_Logo_white_drop_shadow.png"
# description = "My awesome website"
copyright = ":copyright: 2023 Meaty Media All Rights Reserved"

dateFormat = "2 January 2006"

[author]
  name = "Nick (Meaty) Miethe"
  image = "img/nick-profile.png"
  headline = "OpenShift, one *byte* at a time"
  bio = "OCP Advocate, Serial Hobbyist"
  links = [
    { email = "mailto:miethe.dev@gmail.com" },
    { link = "https://distractedhobbyists.com/" },
#    { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    { dev = "https://dev.to/miethe" },
#     { flickr = "https://www.flickr.com/photos/username/" },
    { github = "https://github.com/miethe" },
#    { instagram = "https://instagram.com/username" },
#    { keybase = "https://keybase.io/username" },
    { linkedin = "https://linkedin.com/in/miethe" },
#    { mastodon = "https://mastodon.instance/@username" },
#    { medium = "https://medium.com/username" },
#    { reddit = "https://reddit.com/user/username" },
#    { slack = "https://workspace.url/team/userid" },
#    { twitter = "https://twitter.com/username" },
#    { youtube = "https://youtube.com/username" },
  ]
